name: kata-app-workflow
run-name: ${{ github.actor}} is starting github actions

on:
    push:
      branches:
        - dev-alice


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

         # Step 2: Set up .NET SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        
        # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./TheGreetingKataApp.sln

         # Step 4: Build the solution
      - name: Build the solution
        run: dotnet build ./TheGreetingKataApp.sln --configuration Release --no-restore

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test ./GreeterTests/GreeterTests.csproj --no-build 

        # Step 6: Run tests after code modifications
      - name: Run tests after code modifications
        run: dotnet test ./GreeterTests/GreeterTests.csproj --no-build